### ISSUE TITLE
Unable to write plate files on upload

### ISSUE THREAD

**Issue by mondel9** [alubbock/thunor-web-quickstart#2] opened 2022-12-15 20:46 UTC
### Current Behavior:
When adding plate data to a dataset the upload files and gives an Internal Server Error (500). 

Log out put from Sentry:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp92jsr9u6.upload.tsv'
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "thunorweb/views/datasets.py", line 458, in ajax_upload_platefiles
    results = pfp.parse_all()
  File "thunorweb/plate_parsers.py", line 719, in parse_all
    self.parse_platefile()
  File "thunorweb/plate_parsers.py", line 701, in parse_platefile
    parser(sep=sep)
  File "python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "thunorweb/plate_parsers.py", line 404, in parse_thunor_vanderbilt_hts
    self._create_db_platefile()
  File "thunorweb/plate_parsers.py", line 90, in _create_db_platefile
    self._db_platefile = PlateFile.objects.create(
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "django/db/models/sql/compiler.py", line 1376, in execute_sql
    for sql, params in self.as_sql():
  File "django/db/models/sql/compiler.py", line 1318, in as_sql
    value_rows = [
  File "django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "django/db/models/sql/compiler.py", line 1270, in pre_save_val
    return field.pre_save(obj, add=True)
  File "django/db/models/fields/files.py", line 289, in pre_save
    file.save(file.name, file.file, save=False)
  File "django/db/models/fields/files.py", line 88, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "django/core/files/storage.py", line 268, in _save
    file_move_safe(content.temporary_file_path(), full_path)
  File "django/core/files/move.py", line 56, in file_move_safe
    with open(old_file_name, 'rb') as old_file:
```

### Expected Behavior:
Plate file should upload to proceed to plate mapper

### Steps To Reproduce:
1. Followed the Typical installation Instructions to install (ran all steps as default ubuntu user)
2. Login to thunor web
3. Create dataset --> add plate data

### Environment:
- OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1019-aws x86_64)
- Docker version 20.10.21, build baeda1f
- Docker Compose version v2.12.2

**Comment by alubbock** [comment] 2023-02-05 11:08
Hi @mondel9 , I haven't been able to reproduce this exact issue, but I tried a fresh install on an Ubuntu VM and saw that the permissions on the directory created for plate file uploads are not open enough (due to the default umask settings). I've updated the Thunor Web quickstart installer to set more open permissions on these directories. Please could you give that a try and see if it solves your issue?

**Comment by darrentyson** [comment] 2023-02-05 23:43
Hi @alubbock,

I reinstalled all using the quickstart installation and activated Sentry. Unfortunately, I still get an internal server error 500 with the following output from Sentry with fully annotated data file: 

```
Error 
FileNotFoundError /ajax/platefile/upload 
[Errno 2] No such file or directory: '/tmp/tmpes4rhbj5.upload.csv'  
...
(23 additional frame(s) were not displayed)
...
  File "django/db/models/fields/files.py", line 289, in pre_save
    file.save(file.name, file.file, save=False)
  File "django/db/models/fields/files.py", line 88, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "django/core/files/storage.py", line 268, in _save
    file_move_safe(content.temporary_file_path(), full_path)
  File "django/core/files/move.py", line 56, in file_move_safe
    with open(old_file_name, 'rb') as old_file:
```

When I attempted to upload the unannotated data file I received the following error log from Sentry:  
```
ValueError: I/O operation on closed file.
(23 additional frame(s) were not displayed)
...
  File "django/db/models/fields/files.py", line 289, in pre_save
    file.save(file.name, file.file, save=False)
  File "django/db/models/fields/files.py", line 88, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "django/core/files/storage.py", line 277, in _save
    for chunk in content.chunks():
  File "django/core/files/uploadedfile.py", line 94, in chunks
    self.file.seek(0)
```

Here is a link to the unannotated file I used (~1.3 MB): [VLW001_11T_2Donly_Thunor_unannot.csv](https://www.dropbox.com/s/vsltkwr72i0hctb/VLW001_11T_2Donly_Thunor_unannot.csv?dl=0)

**Comment by alubbock** [comment] 2023-02-06 14:48
@darrentyson Thanks for the file - with that, I was able to reproduce the error. Looks like it was a [pandas bug](https://github.com/pandas-dev/pandas/issues/36980) that was prematurely closing the file. I've upgraded the pandas dependency in the container and this fixes the issue for me. Please could you confirm this works for you?

You can upgrade an existing installation with `git pull` then `python thunorctl.py upgrade`.

**Comment by alubbock** [comment] 2023-02-06 20:25
Confirmed resolved by email

**Closed as completed by alubbock** 2023-02-06 20:25 UTC
